export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const GET_GRADED_ASSIGNMENT_LIST_START =
  "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL =
  "GET_GRADED_ASSIGNMENTS_LIST_FAIL";
export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS =
  "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";

export const QUIZ_HANDLE_NEXT = "QUIZ_HANDLE_NEXT";
export const QUIZ_HANDLE_START = "QUIZ_HANDLE_START";
export const QUIZ_HANDLE_VALIDATE = "QUIZ_HANDLE_VALIDATE";
export const QUIZ_HANDLE_RESTART = "QUIZ_HANDLE_RESTART";

export const SET_COURSE_DETAISL = "SET_COURSE_DETAISL";
export const RESET_COURSE_DETAISL = "RESET_COURSE_DETAISL";

export const GET_COURSELIST_START = "GET_COURSELIST_START";
export const GET_COURSELIST_FAIL = "GET_COURSELIST_FAIL";
export const GET_COURSELIST_SUCCESS = "GET_COURSELIST_SUCCESS";

export const GET_COURSE_START = "GET_COURSE_START";
export const GET_COURSE_FAIL = "GET_COURSE_FAIL";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";

export const GET_UNIT_START = "GET_UNIT_START";
export const GET_UNIT_FAIL = "GET_COURSE_FAIL";
export const GET_UNIT_SUCCESS = "GET_UNIT_FAIL";

export const GET_LESSON_START = "GET_LESSON_START";
export const GET_LESSON_FAIL = "GET_LESSON_FAIL";
export const GET_LESSON_SUCCESS = "GET_LESSON_SUCCESS";
export const LESSON_RESET = "LESSON_RESET";

export const GET_QUIZ_START = "GET_QUIZ_START";
export const GET_QUIZ_FAIL = "GET_QUIZ_FAIL";
export const GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";
